# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\Windows\TEMP\abs_9baec568-e71e-4795-b66d-95ef93f01d2fcx4xmo47\clone\recipe, last modified Thu Jun 23 13:45:21 2022
# ------------------------------------------------

package:
  name: getopt-win32
  version: '0.1'
source:
  sha256: 7e9653ecd58ce4149959bf6a905f4ab2f7889856fe1218afbf84284074f9e549
  url: https://github.com/libimobiledevice-win32/getopt/archive/0.1.tar.gz
build:
  number: '0'
  run_exports:
    - getopt-win32 >=0.1,<0.2.0a0
  string: h2bbff1b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - ninja-base 1.10.2 h6d14046_5
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_2
    - zstd 1.5.2 h19a0ad4_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\getopt.h   exit 1
    - if not exist %LIBRARY_LIB%\getopt.lib exit 1
    - if not exist %LIBRARY_BIN%\getopt.dll exit 1
about:
  dev_url: https://github.com/libimobiledevice-win32/getopt
  doc_url: https://github.com/libimobiledevice-win32/getopt/blob/master/article.md
  home: https://vcpkg.info/port/getopt-win32
  license: LGPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A port of getopt for Visual C++
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9baec568-e71e-4795-b66d-95ef93f01d2f
  recipe-maintainers:
    - nehaljwani
  remote_url: git@github.com:AnacondaRecipes/getopt-win32-feedstock.git
  sha: 0545e76f71dc85a149d8f0cc691d0df865164b52
