# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_3482sapb2p\clone\recipe, last modified Tue Sep 27 13:51:29 2022
# ------------------------------------------------

package:
  name: expat
  version: 2.4.9
source:
  sha256: 7f44d1469b110773a94b0d5abeeeffaef79f8bd6406b07e52394bcf48126437a
  url: https://github.com/libexpat/libexpat/releases/download/R_2_4_9/expat-2.4.9.tar.bz2
build:
  number: '0'
  run_exports:
    - expat >=2.4.9,<3.0a0
  string: h6c2663c_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_3
    - zstd 1.5.2 h19a0ad4_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - xmlwf -h
about:
  dev_url: https://github.com/libexpat/libexpat
  doc_source_url: https://github.com/libexpat/libexpat/tree/master/expat/doc
  doc_url: https://libexpat.github.io/doc/
  home: https://libexpat.github.io
  license: MIT
  license_family: MIT
  license_file: COPYING
  license_url: https://github.com/libexpat/libexpat/blob/master/expat/COPYING
  summary: Expat XML parser library in C
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 34b817fb-b6ab-4988-b98a-2ab885aab08e
  recipe-maintainers:
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/expat-feedstock.git
  sha: 31b6428956c9263e559e4874019dc942e5a0f489
