# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\Users\builder\adipietro\aggregate\glib-feedstock\recipe, last modified Thu Jan 20 07:47:06 2022
# ------------------------------------------------

package:
  name: glib
  version: 2.69.1
source:
  patches:
    - patches/0001-replace-hardcoded-paths.patch
    - patches/0002-skip-some-tests.patch
    - patches/0003-add-install_rpath-to-meson-build-files.patch
    - patches/0005-Increase-some-test-timeouts.patch
  sha256: f92f34057a091fc8638d91f10cece842cb8618e9a1090b0ddb19cc15a21bf39c
  url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.69/glib-2.69.1.tar.xz
build:
  ignore_run_exports:
    - libffi
  number: '1'
  run_exports:
    - glib >=2.69.1,<3.0a0
  string: h5dc1a3c_1
requirements:
  build:
    - ca-certificates 2021.10.26 haa95532_2
    - certifi 2021.10.8 py38haa95532_2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - m2w64-pkg-config 0.29.1 2
    - meson 0.53.2 py_0
    - msys2-conda-epoch 20160418 1
    - ninja 1.10.2 py38h559b2a2_3
    - openssl 1.1.1m h2bbff1b_0
    - pip 21.2.2 py38haa95532_0
    - python 3.8.12 h6244533_0
    - setuptools 58.0.4 py38haa95532_0
    - sqlite 3.37.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  host:
    - ca-certificates 2021.10.26 haa95532_2
    - certifi 2021.10.8 py38haa95532_2
    - libffi 3.2.1 ha925a31_1007
    - libiconv 1.15 h1df5818_7
    - m2w64-gcc-libgfortran 5.3.0 6
    - m2w64-gcc-libs 5.3.0 7
    - m2w64-gcc-libs-core 5.3.0 7
    - m2w64-gmp 6.1.0 2
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - msys2-conda-epoch 20160418 1
    - openssl 1.1.1m h2bbff1b_0
    - pcre 8.45 hd77b12b_0
    - pip 21.2.2 py38haa95532_0
    - python 3.8.12 h6244533_0
    - setuptools 58.0.4 py38haa95532_0
    - sqlite 3.37.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
    - zlib 1.2.11 h8cc25b3_4
  run:
    - libffi >=3.3
    - libiconv >=1.15,<2.0a0
    - pcre >=8.45,<9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - gdbus help
    - gio version
    - gio-querymodules .
    - glib-compile-resources --help
    - glib-compile-schemas --help
    - gobject-query --help
    - gresource help
about:
  description: 'GLib provides the core application building blocks for libraries and

    applications written in C. It provides the core object system used in

    GNOME, the main loop implementation, and a large set of utility functions

    functions for strings and common data structures.

    '
  dev_url: https://git.gnome.org/browse/glib/
  doc_source_url: https://git.gnome.org/browse/glib/tree/docs
  doc_url: https://developer.gnome.org/glib/unstable/
  home: https://developer.gnome.org/glib/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Provides core application building blocks for libraries and applications
    written in C.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - chenghlee
    - isuruf
    - jakirkham
    - ocefpaf
    - pkgw
    - scopatz
