# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\ci\containers\00003shgk56\tmp\build\80754af9\rsync-recipes\graphviz-2.50.0-on-winbuilder, last modified Thu Jun 30 14:57:53 2022
# ------------------------------------------------

package:
  name: graphviz
  version: 2.50.0
source:
  - patches:
      - patches/0001-Always-link-to-getopt-on-Windows.patch
      - patches/0002-Remove-requirement-of-hard-coded-DLLs-in-PATH.patch
      - patches/0003-Add-support-for-GTS-in-CMake-builds.patch
      - patches/0004-Fix-logic-for-finding-harfbuzz.patch
    sha256: afa48581f764a35e148909cc96a0308ec2356b5225b64af12492f3392f20ef1c
    url: https://gitlab.com/graphviz/graphviz/-/archive/2.50.0/graphviz-2.50.0.tar.gz
  - folder: ltdl_compat
    sha256: a3cf376bca2965634ba05926d4065a46331e71c487d84a4c6aceb795e9458bfd
    url: https://gitlab.com/graphviz/graphviz-windows-dependencies/-/raw/c7eafb3c/x64/include/ltdl.h
build:
  ignore_run_exports:
    - fontconfig
    - freetype
    - gdk-pixbuf
    - pixman
  number: '0'
  string: hdb8b0d4_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.4.26 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 hd77b12b_4
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - m2-bash 4.3.042 5
    - m2-bison 3.0.4 2
    - m2-flex 2.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gmp 6.1.0 3
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-libreadline 6.3.008 8
    - m2-m4 1.4.17 5
    - m2-mpfr 3.1.4 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1p h2bbff1b_0
    - perl 5.26.2.1 h0c8e037_0
    - python 3.10.4 hbb2ffb3_0
    - sqlite 3.38.5 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_2
    - zstd 1.5.2 h19a0ad4_0
  host:
    - cairo 1.16.0 he04af86_2
    - expat 2.2.10 h33f27b4_2
    - freetype 2.10.4 hd328e21_0
    - fribidi 1.0.10 h62dcd97_0
    - getopt-win32 0.1 h2bbff1b_0
    - glib 2.69.1 h5dc1a3c_1
    - graphite2 1.3.14 hd77b12b_1
    - gts 0.7.6 h63ab5a1_3
    - harfbuzz 4.3.0 hda2c7e1_0
    - icu 58.2 ha925a31_3
    - jpeg 9e h2bbff1b_0
    - libffi 3.4.2 hd77b12b_4
    - libgd 2.3.3 ha43c60c_1
    - libiconv 1.16 h2bbff1b_2
    - libpng 1.6.37 h2a8f88b_0
    - libtiff 4.2.0 he0120a3_1
    - lz4-c 1.9.3 h2bbff1b_1
    - pango 1.50.7 h78c2152_0
    - pcre 8.45 hd77b12b_0
    - pixman 0.40.0 h2bbff1b_1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_2
    - zstd 1.5.2 h19a0ad4_0
  run:
    - cairo >=1.16.0,<2.0a0
    - expat >=2.2.10,<3.0a0
    - getopt-win32 >=0.1,<0.2.0a0
    - glib >=2.69.1,<3.0a0
    - gts >=0.7.6,<0.8.0a0
    - libgd >=2.3.3,<2.4.0a0
    - pango >=1.50.7,<2.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  files:
    - sample.dot
about:
  description: 'Graphviz is an open source graph visualization software. Graph visualization

    is a way of representing structural information as diagrams of abstract

    graphs and networks.

    '
  dev_url: https://gitlab.com/graphviz/graphviz/
  doc_source_url: https://gitlab.com/graphviz/graphviz.gitlab.io
  doc_url: https://graphviz.gitlab.io/documentation/
  home: https://www.graphviz.org/
  license: EPL-1.0
  license_family: Other
  license_file: COPYING
  summary: Open Source graph visualization software.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - johanneskoester
    - nehaljwani
    - ocefpaf
