# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\ci\containers\00003shgk3q\tmp\build\80754af9\rsync-recipes\harfbuzz-4.3.0-on-winbuilder, last modified Tue Jun 28 16:01:17 2022
# ------------------------------------------------

package:
  name: harfbuzz
  version: 4.3.0
source:
  sha256: 32184860ddc0b264ff95010e1c64e596bd746fe4c2e34014a1185340cdddeba6
  url: https://github.com/harfbuzz/harfbuzz/archive/4.3.0.tar.gz
build:
  ignore_run_exports:
    - pixman
  number: '0'
  run_exports:
    - harfbuzz >=4.3.0,<5.0a0
  string: hda2c7e1_0
requirements:
  build:
    - ca-certificates 2022.4.26 haa95532_0
    - certifi 2022.6.15 py39haa95532_0
    - glib 2.69.1 h1491ce7_0
    - gobject-introspection 1.68.0 py39hf5b05f3_2
    - libffi 3.2.1 ha925a31_1007
    - libiconv 1.16 h2bbff1b_2
    - m2w64-gcc-libgfortran 5.3.0 6
    - m2w64-gcc-libs 5.3.0 7
    - m2w64-gcc-libs-core 5.3.0 7
    - m2w64-gmp 6.1.0 2
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - meson 0.59.0 pyhd3eb1b0_0
    - msys2-conda-epoch 20160418 1
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1p h2bbff1b_0
    - pcre 8.45 hd77b12b_0
    - pkg-config 0.29.2 h8cc25b3_0
    - pthread-stubs 0.3 h3c9f919_1
    - python 3.9.12 h6244533_0
    - setuptools 61.2.0 py39haa95532_0
    - sqlite 3.38.5 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - wincertstore 0.2 py39haa95532_2
    - zlib 1.2.12 h8cc25b3_2
  host:
    - ca-certificates 2022.4.26 haa95532_0
    - freetype 2.10.4 hd328e21_0
    - glib 2.69.1 h1491ce7_0
    - gobject-introspection 1.68.0 py39hf5b05f3_2
    - graphite2 1.3.14 hd77b12b_1
    - icu 58.2 ha925a31_3
    - libffi 3.2.1 ha925a31_1007
    - libiconv 1.16 h2bbff1b_2
    - libpng 1.6.37 h2a8f88b_0
    - m2w64-gcc-libgfortran 5.3.0 6
    - m2w64-gcc-libs 5.3.0 7
    - m2w64-gcc-libs-core 5.3.0 7
    - m2w64-gmp 6.1.0 2
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - msys2-conda-epoch 20160418 1
    - openssl 1.1.1p h2bbff1b_0
    - pcre 8.45 hd77b12b_0
    - pkg-config 0.29.2 h8cc25b3_0
    - python 3.9.12 h6244533_0
    - sqlite 3.38.5 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.12 h8cc25b3_2
  run:
    - freetype >=2.10.4,<3.0a0
    - glib >=2.69.1,<3.0a0
    - graphite2 >=1.3.14,<2.0a0
    - icu >=58.2,<59.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %PREFIX%\Library\bin\harfbuzz-icu.dll exit 1
    - if not exist %PREFIX%\Library\bin\harfbuzz.dll exit 1
    - if not exist %PREFIX%\Library\include\harfbuzz\hb-ft.h exit 1
about:
  description: "HarfBuzz is a text shaping library. Using the HarfBuzz library allows\n\
    programs to convert a sequence of Unicode input into properly formatted\nand positioned\
    \ glyph output\u2014for any writing system and language.\n"
  dev_url: https://github.com/harfbuzz/harfbuzz
  doc_url: https://harfbuzz.github.io/
  home: https://harfbuzz.github.io/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A text shaping library.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pkgw
