# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\ci\containers\00003mcml8e\tmp\build\80754af9\rsync-recipes\libffi-3.4.2-on-winbuilder, last modified Fri Jun 10 11:29:58 2022
# ------------------------------------------------

package:
  name: libffi
  version: 3.4.2
source:
  patches:
    - 0002-Don-t-define-FFI_COMPLEX_TYPEDEF-ifndef-FFI_TARGET_H.patch
    - fix_w3264_masm.patch
    - win_cmake.patch
  sha256: 540fb721619a6aba3bdeef7d940d8e9e0e6d2c193595bc243241b77ff9e93620
  url: https://github.com/libffi/libffi/releases/download/v3.4.2/libffi-3.4.2.tar.gz
build:
  number: '4'
  run_exports:
    - libffi >=3.4,<4.0a0
  string: hd77b12b_4
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_2
    - zstd 1.5.2 h19a0ad4_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  requires:
    - cmake
    - llvm-tools
    - m2-grep
    - vs2017_win-64
  source_files:
    - testsuite
    - testsuite/libffi.bhaible
about:
  description: 'The libffi library provides a portable, high level programming interface

    to various calling conventions. This allows a programmer to call any

    function specified by a call interface description at run-time.

    '
  dev_url: https://github.com/libffi/libffi
  doc_url: https://sourceware.org/libffi/
  home: https://sourceware.org/libffi/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Portable Foreign Function Interface Library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - scopatz
    - stefan-balke
